In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta

In [2]:
data = yf.download(tickers = 'TSLA', start = '2023-12-20', end = '2024-9-9')
data.head(10)

[*********************100%%**********************]  1 of 1 completed

C:\Users\David\anaconda3\envs\main\lib\site-packages\yfinance\utils.py:771: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-12-20,256.410004,259.839996,247.000000,247.139999,247.139999,125097000
2023-12-21,251.899994,254.800003,248.550003,254.500000,254.500000,109594200
2023-12-22,256.760010,258.220001,251.369995,252.539993,252.539993,93249800
2023-12-26,254.490005,257.970001,252.910004,256.609985,256.609985,86892400
2023-12-27,258.350006,263.339996,257.519989,261.440002,261.440002,106494400
2023-12-28,263.660004,265.130005,252.710007,253.179993,253.179993,113619900
2023-12-29,255.100006,255.190002,247.429993,248.479996,248.479996,100615300
2024-01-02,250.080002,251.250000,244.410004,248.419998,248.419998,104654200
2024-01-03,244.979996,245.679993,236.320007,238.449997,238.449997,121082600
2024-01-04,239.250000,242.699997,237.729996,237.929993,237.929993,102629300

In [3]:
# Adding indicators
data['RSI']=ta.rsi(data.Close, length=15)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)

data['Target'] = data['Adj Close']-data.Open
data['Target'] = data['Target'].shift(-1)

data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace=True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close', 'Date'], axis=1, inplace=True)

C:\Users\David\AppData\Local\Temp\ipykernel_13512\2358861191.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

In [4]:
data.head(2)

,Open,High,Low,Adj Close,RSI,EMAF,EMAM,EMAS,Target,TargetClass,TargetNextClose
0,221.190002,222.279999,215.330002,219.800003,47.610652,231.054429,204.091350,195.394000,7.200012,1,232.100006
1,224.899994,234.270004,224.699997,232.100006,53.127840,231.154007,204.645977,195.880172,-9.630005,0,222.619995

In [5]:
data_set = data.iloc[:, 0:11]#.values
pd.set_option('display.max_columns', None)

data_set.head(20)
#print(data_set.shape)
#print(data.shape)
#print(type(data_set))

,Open,High,Low,Adj Close,RSI,EMAF,EMAM,EMAS,Target,TargetClass,TargetNextClose
0,221.190002,222.279999,215.330002,219.800003,47.610652,231.054429,204.091350,195.394000,7.200012,1,232.100006
1,224.899994,234.270004,224.699997,232.100006,53.127840,231.154007,204.645977,195.880172,-9.630005,0,222.619995
2,232.250000,232.410004,220.000000,222.619995,48.877257,230.341244,205.001898,196.234342,4.170013,1,232.070007
3,227.899994,234.679993,226.789993,232.070007,52.901807,230.505888,205.537901,196.708987,-10.830002,0,216.860001
4,227.690002,231.869995,214.330002,216.860001,46.578440,229.206280,205.762101,196.975887,-7.210007,0,207.669998
5,214.880005,216.130005,205.779999,207.669998,43.233076,227.155206,205.799881,197.117531,13.660004,1,198.880005
6,185.220001,203.880005,182.000000,198.880005,40.269151,224.462329,205.662854,197.140875,-0.110001,0,200.639999
7,200.750000,202.899994,192.669998,200.639999,41.134906,222.193536,205.563391,197.187221,-9.010010,0,191.759995
8,200.770004,203.490005,191.479996,191.759995,38.146012,219.295104,205.290057,197.115338,3.139999,1,198.839996
9,195.699997,200.699997,192.039993,198.839996,41.760925,217.346998,205.162333,197.138181,2.949997,1,200.000000
10,197.050003,200.880005,195.110001,200.000000,42.352351,215.694903,205.060108,197.176086,-1.529999,0,197.490005
11,199.020004,199.259995,194.669998,197.490005,41.378182,213.961103,204.910205,197.180243,9.360001,1,207.830002
12,198.470001,208.490005,197.059998,207.830002,46.781160,213.377189,204.968023,197.321300,-6.009995,0,201.380005
13,207.389999,208.440002,198.750000,201.380005,44.066680,212.234600,204.896973,197.375058,9.119995,1,214.139999
14,205.020004,215.880005,204.820007,214.139999,50.192504,212.416066,205.080003,197.597110,4.970001,1,216.119995
15,211.149994,219.800003,210.800003,216.119995,51.083199,212.768822,205.298617,197.842446,5.649994,1,222.720001
16,217.070007,222.979996,214.089996,222.720001,54.019822,213.716553,205.643595,198.171950,-3.779999,0,221.100006
17,224.880005,228.220001,219.559998,221.100006,53.180221,214.419739,205.949662,198.475633,0.600006,1,223.270004
18,222.669998,224.660004,218.860001,223.270004,54.201811,215.262621,206.292639,198.804035,-13.160004,0,210.660004
19,223.820007,224.800003,210.320007,210.660004,47.719073,214.824277,206.379122,198.961068,5.860001,1,220.320007

In [6]:
#Target column Categories
#y =[1 if data.Open[i]>data.Close[i] else 0 for i in range(0, len(data))]
#yi = [data.Open[i]-data.Close[i] for i in range(0, len(data))]
#print(yi)
#print(len(yi))

In [7]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)

[[0.764831   0.64409627 0.74413947 0.69509173 0.47543499 0.99473668
  0.         0.         0.81818213 1.         1.        ]
 [0.84371664 0.97957483 0.95333787 1.         0.75257862 1.
  0.15296897 0.09141849 0.34449763 0.         0.76499732]
 [1.         0.92753229 0.84840379 0.76499732 0.53906008 0.95704078
  0.25113387 0.15801561 0.73290215 1.         0.99925635]
 [0.90750572 0.99104624 1.         0.99925635 0.74122436 0.96574317
  0.39896605 0.24726647 0.31072345 0.         0.62221118]
 [0.90304066 0.91242293 0.72181305 0.62221118 0.42358415 0.89705136
  0.46080158 0.29745377 0.412609   0.         0.3943976 ]
 [0.63066137 0.47202036 0.53092213 0.3943976  0.25553724 0.78864022
  0.47122154 0.32408809 1.         1.         0.17649996]
 [0.         0.1292672  0.         0.17649996 0.10665112 0.64630615
  0.43342871 0.32847763 0.61244022 0.         0.22012896]
 [0.33021474 0.10184664 0.23822281 0.22012896 0.15014037 0.52638732
  0.40599645 0.33719241 0.36194752 0.         0.        ]
 [0.33064009 0.11835507 0.21165432 0.         0.         0.37318841
  0.33060935 0.32367558 0.70391218 1.         0.17550818]
 [0.2228364  0.04029105 0.22415706 0.17550818 0.18158704 0.27021978
  0.29538242 0.32797094 0.69856452 1.         0.20426384]
 [0.25154161 0.04532765 0.29269932 0.20426384 0.21129603 0.18289701
  0.26718839 0.33509847 0.57247407 0.         0.14204287]
 [0.2934298  0.         0.28287564 0.14204287 0.16236081 0.09125568
  0.22584436 0.33588031 0.87897548 1.         0.39836397]
 [0.28173507 0.25825432 0.33623576 0.39836397 0.43376731 0.06039243
  0.2417908  0.36240417 0.44638361 0.         0.23847317]
 [0.47140121 0.25685525 0.37396746 0.23847317 0.2974115  0.
  0.22219488 0.37251261 0.87222047 1.         0.55478429]
 [0.42100794 0.4650254  0.50948897 0.55478429 0.60512855 0.00959156
  0.27267556 0.4142667  0.75541798 1.         0.60386697]
 [0.55135006 0.57470636 0.64300083 0.60386697 0.64987062 0.0282367
  0.33297036 0.46039905 0.77455653 1.         0.7674764 ]
 [0.67722745 0.66368208 0.71645459 0.7674764  0.7973853  0.07832978
  0.42811706 0.52235808 0.50914732 0.         0.72731788]
 [0.84329162 0.81029665 0.83858011 0.72731788 0.75520983 0.11549723
  0.51253208 0.57946177 0.63242352 1.         0.78111058]
 [0.79630019 0.71068845 0.82295169 0.78111058 0.80652715 0.16004843
  0.60712694 0.64121362 0.24514504 0.         0.46851769]
 [0.82075286 0.71460561 0.63228425 0.46851769 0.48088128 0.13687939
  0.63097925 0.67074162 0.78046721 1.         0.70798227]
 [0.62173094 0.62171231 0.71913399 0.70798227 0.71564537 0.16454426
  0.70711725 0.72393733 0.4596119  0.         0.53173044]
 [0.71294917 0.55484048 0.64768919 0.53173044 0.54233309 0.15378346
  0.74291637 0.75872058 0.50182972 0.         0.43257331]
 [0.59600254 0.4588698  0.55682086 0.43257331 0.44847044 0.12391197
  0.75616064 0.78308089 0.50379966 0.         0.34680222]
 [0.52094409 0.35198657 0.45970081 0.34680222 0.36766025 0.07946811
  0.75024586 0.79850119 0.51646493 0.         0.35994051]
 [0.52264517 0.4373252  0.53516421 0.35994051 0.38293917 0.04192495
  0.74734278 0.81503724 0.76977189 1.         0.55404065]
 [0.49776747 0.42837187 0.55883015 0.55404065 0.60392867 0.04737264
  0.78726066 0.85085536 0.48437982 0.         0.4670304 ]
 [0.6387411  0.57750409 0.61710211 0.4670304  0.50942111 0.03463261
  0.80721829 0.87745722 0.86377725 1.         0.68542393]
 [0.53944282 0.64241755 0.63786585 0.68542393 0.74739884 0.06745441
  0.87489643 0.92564855 0.80354607 1.         0.95215649]
 [0.81373603 1.         0.89863822 0.95215649 1.         0.15131489
  1.         1.         0.         0.         0.47025275]]

In [8]:
# multiple feature from data provided to the model
X = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 30
print(data_set_scaled.shape[0])
for j in range(8):#data_set_scaled[0].size):#2 columns are target not X
    X.append([])
    for i in range(backcandles, data_set_scaled.shape[0]):#backcandles+2
        X[j].append(data_set_scaled[i-backcandles:i, j])

#move axis from 0 to position 2
X=np.moveaxis(X, [0], [2])

#Erase first elements of y because of backcandles to match X length
#del(yi[0:backcandles])
#X, yi = np.array(X), np.array(yi)
# Choose -1 for last column, classification else -2...
X, yi =np.array(X), np.array(data_set_scaled[backcandles:,-1])
y=np.reshape(yi,(len(yi),1))
#y=sc.fit_transform(yi)
#X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X)
print(X.shape)
print(y)
print(y.shape)

29

AxisError: destination: axis 2 is out of bounds for array of dimension 2